### ISSUE TITLE
Pull parameter descriptions from Node itself

### ISSUE THREAD

**Issue by jonselling** [3473f/ros2autodoc#27]
I thought this effort was neat, and I wanted to note that each parameter can have a `ParameterDescriptor` that you can possibly access to get descriptions and some other information (like bounds) about a parameter.

I believe rqt_reconfigure pulls this information from the parameters if you wanted an example.

I also created an issue ( https://github.com/ros2/rclcpp/issues/2286 ) to add string descriptions to all ROS interfaces that this can also support from (and this is basically what I am looking for documentation wise)

**Comment by 3473f** [comment]
Thanks for the tip! We have been using the tool for a few months now and I have a few things planne and this would definitely be a nice quality-of-life feature to include. I am extremely busy right now, but should have time for it in the first week of september so it should be coming soon! :)

**Comment by 3473f** [comment]
@jonselling had a bit of time on my hand tonight so I decided to implement this. It would be neat if all interfaces included a description as well .. we will see how it goes with the other feature request.

**Comment by jonselling** [comment]
@3473f This is honestly extremely fast and not expected :laughing:. Great job!

I haven't started to test this plugin yet, but it seems like something my team might be interested in using.

I know we have been filling in the ParameterDescriptors where possible if we found a tool that could automatically pull them, so I just wanted to mention them as an option to you. Again, great job getting it done as fast as you did!

**Comment by 3473f** [comment]
It was quite easy since I was making the API call to get the parameter info to get the data type, so I only needed to access the description field as well.

It's about time we started using the ParameterDescriptors as well (: We usually have a lot of interfaces, and it was tedious to list all of them manually, so having the tool generate a complete list and manually filling in the description saved us a lot of time.

It would be great to get feedback from you once you have tested it! 😄
